# This file was generated by GoReleaser. DO NOT EDIT.
cask "arcane-cli" do
  version "1.17.3"

  on_macos do
    on_intel do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_darwin_amd64.tar.gz"
      sha256 "19c1e35f96dc2f41c50fd15e3fec1285ed6a6f89b9330109b6c2ce13e4020332"
    end
    on_arm do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_darwin_arm64.tar.gz"
      sha256 "f2a0fe9fc68ebe4aa2f0df9f07e754e4d69913c248f13b1d19f385213f1753e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_linux_amd64.tar.gz"
      sha256 "8411b787a44d7b3622fc4e86e08d7b15a784c071166bf426c509a38038a2eb94"
    end
    on_arm do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_linux_arm64.tar.gz"
      sha256 "6a21fe1a1017ac7789830e734786f6246ab8c88acd493c7ebc7b011921f468cc"
    end
  end

  name "arcane-cli"
  desc "Arcane CLI - Modern Docker Management, Designed for Everyone."
  homepage "https://getarcane.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arcane-cli"
  bash_completion "completions/arcane-cli.bash"
  fish_completion "completions/arcane-cli.fish"
  zsh_completion "completions/arcane-cli.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arcane-cli"]
    end
  end

  # No zap stanza required

end
