# This file was generated by GoReleaser. DO NOT EDIT.
cask "arcane-cli" do
  version "1.17.0"

  on_macos do
    on_intel do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_darwin_amd64.tar.gz"
      sha256 "b6d45db35844a9f64bde745e3e462f675c354e2ecef6437ffbf144dfcf7e02cc"
    end
    on_arm do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_darwin_arm64.tar.gz"
      sha256 "8ea9ea49487e527d2201a251a47c332accfc2564f03465a5fd99541e67977c0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_linux_amd64.tar.gz"
      sha256 "c949ce0ffe09f2f875581138df02a46862c98c6122fb29171da3087c953a62e7"
    end
    on_arm do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_linux_arm64.tar.gz"
      sha256 "5dacff1206a86aff12be4fef54a4f7cc7bc15b882debd583f643aa42fa961643"
    end
  end

  name "arcane-cli"
  desc "Arcane CLI - Modern Docker Management, Designed for Everyone."
  homepage "https://getarcane.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arcane-cli"
  bash_completion "completions/arcane-cli.bash"
  fish_completion "completions/arcane-cli.fish"
  zsh_completion "completions/arcane-cli.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arcane-cli"]
    end
  end

  # No zap stanza required

end
