# This file was generated by GoReleaser. DO NOT EDIT.
cask "arcane-cli" do
  name "arcane-cli"
  desc "Arcane CLI - Modern Docker Management, Designed for Everyone."
  homepage "https://getarcane.app"
  version "1.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arcane-cli"

  on_macos do
    on_intel do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_darwin_amd64.tar.gz"
      sha256 "8b1b2cdc53df4070f1f93a9068e09d98292baff5728d3c955524687671c8e6ca"
    end
    on_arm do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_darwin_arm64.tar.gz"
      sha256 "881b6b3591c76ad6e3237a297b8246fa9d0aa9b13d3e692f2485b27e4596b8f5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_linux_amd64.tar.gz"
      sha256 "d4d18dbca2890dac181cd8377b3e8e9faeb6e83be778763b5f3b9f3d7acb77b9"
    end
    on_arm do
      url "https://github.com/getarcaneapp/arcane/releases/download/v#{version}/arcane-cli_linux_arm64.tar.gz"
      sha256 "52c3fbb1f6e7380472b9c63280996a745e01eb9d73e7aa6f77e3635c6e0a3b49"
    end
  end

  # No zap stanza required
end
